export const LOG_IN = 'LOG_IN'
export const LOG_OUT = 'LOG_OUT'
export const CHECK_LOGIN = 'CHECK_LOGIN'
export const MODIFY_DATA = 'MODIFY_DATA'
export const LOG_IN_ERROR = 'LOG_IN_ERROR'
export const TOKEN_UPDATED = 'TOKEN_UPDATED'
export const LOCALE_UPDATED = 'LOCALE_UPDATED'